ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS kanban_status VARCHAR(50) DEFAULT 'new',
  ADD COLUMN IF NOT EXISTS source VARCHAR(100) DEFAULT 'website',
  ADD COLUMN IF NOT EXISTS region VARCHAR(100),
  ADD COLUMN IF NOT EXISTS deal_amount INTEGER,
  ADD COLUMN IF NOT EXISTS commission_rate NUMERIC(5,2) DEFAULT 5.00,
  ADD COLUMN IF NOT EXISTS commission_amount INTEGER,
  ADD COLUMN IF NOT EXISTS commission_paid BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS manager VARCHAR(100),
  ADD COLUMN IF NOT EXISTS messenger VARCHAR(50),
  ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE products
  ADD COLUMN IF NOT EXISTS views_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS orders_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sales_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_revenue INTEGER DEFAULT 0;
